services:
  ai-discord-bot:
    build:
      context: .
    pull_policy: build
    env_file:
      - stack.env
    volumes:
      - db-data:/app/database
    restart: unless-stopped

volumes:
  db-data:
